using System.Collections.Generic;

namespace AccardND.Localization.Editor
{
    internal readonly struct ItalianTextEntry
    {
        public ItalianTextEntry(string key, string text)
        {
            Key = key;
            Text = text;
        }

        public string Key { get; }
        public string Text { get; }
        public bool IsSmart => Text.Contains("{");
    }

    /// <summary>
    /// Sorgente italiana iniziale. Il builder la riversa nella String Table "Game".
    /// Aggiungere qui ogni nuovo testo prima di usarne la chiave nel codice.
    /// </summary>
    internal static class ItalianGameTextCatalog
    {
        public static readonly IReadOnlyList<ItalianTextEntry> Entries = new ItalianTextEntry[]
        {
            new(GameTextKeys.Common.Activate, "ATTIVA"),
            new(GameTextKeys.Common.Back, "INDIETRO"),
            new(GameTextKeys.Common.Cancel, "ANNULLA"),
            new(GameTextKeys.Common.Close, "CHIUDI"),
            new(GameTextKeys.Common.Confirm, "CONFERMA"),
            new(GameTextKeys.Common.Continue, "CONTINUA"),
            new(GameTextKeys.Common.Card, "Carta"),
            new(GameTextKeys.Common.Cpu, "CPU"),
            new(GameTextKeys.Common.Exit, "ESCI"),
            new(GameTextKeys.Common.Mute, "MUTE"),
            new(GameTextKeys.Common.Muted, "MUTO"),
            new(GameTextKeys.Common.Opponent, "AVVERSARIO"),
            new(GameTextKeys.Common.Proceed, "PROCEDI"),
            new(GameTextKeys.Common.Use, "USA"),
            new(GameTextKeys.Common.You, "TU"),

            new(GameTextKeys.Login.Title, "ACCEDI"),
            new(GameTextKeys.Login.Subtitle, "ENTRA NEL REGNO"),
            new(GameTextKeys.Login.InitialStatus, "Controllo aggiornamenti e accesso al tuo account di gioco."),
            new(GameTextKeys.Login.GoogleRequired, "Accedi con Google per continuare."),
            new(GameTextKeys.Login.RestoringSession, "Ripristino sessione..."),
            new(GameTextKeys.Login.WelcomeBack, "Bentornato ({0})."),
            new(GameTextKeys.Login.GoogleButton, "ACCEDI GOOGLE"),
            new(GameTextKeys.Login.NicknamePlaceholder, "NICKNAME"),
            new(GameTextKeys.Login.UpdateTitle, "AGGIORNA IL GIOCO"),
            new(GameTextKeys.Login.UpdateNow, "AGGIORNA ORA"),
            new(GameTextKeys.Login.UpdateRequiredGeneric, "una versione più recente"),
            new(GameTextKeys.Login.UpdateRequiredVersion, "la versione {0}"),
            new(GameTextKeys.Login.UpdateMessage, "Il tuo gioco è alla versione {0}, ma per giocare serve {1}.\n\nAggiorna il gioco e riavvialo per continuare."),
            new(GameTextKeys.Login.VersionOutdated, "Versione non aggiornata."),
            new(GameTextKeys.Login.AccessFailed, "Accesso non riuscito: {0}\nPuoi riprovare con Google."),
            new(GameTextKeys.Login.CheckingUpdates, "Controllo aggiornamenti..."),
            new(GameTextKeys.Login.Updated, "Gioco aggiornato."),
            new(GameTextKeys.Login.AccessingProvider, "Accesso con {0}..."),
            new(GameTextKeys.Login.AccessComplete, "Accesso completato ({0})."),
            new(GameTextKeys.Login.CheckingAccount, "Controllo account di gioco..."),
            new(GameTextKeys.Login.GoogleAccountRequired, "Accedi con Google per scegliere o recuperare il tuo account."),
            new(GameTextKeys.Login.ChooseNickname, "Scegli un nickname unico per continuare."),
            new(GameTextKeys.Login.NicknameTooShort, "Il nickname deve avere almeno 3 caratteri."),
            new(GameTextKeys.Login.CheckingNickname, "Controllo nickname..."),
            new(GameTextKeys.Login.Welcome, "Benvenuto, {0}."),
            new(GameTextKeys.Login.NicknameUnavailable, "Nickname non disponibile. Scegline un altro."),
            new(GameTextKeys.Login.OpeningMenu, "Apro il menu..."),
            new(GameTextKeys.Login.AuthenticationUnavailable, "Unity Authentication non disponibile."),
            new(GameTextKeys.Login.MissingToken, "token mancante"),
            new(GameTextKeys.Login.MissingAccountToken, "token account non disponibile"),
            new(GameTextKeys.Login.AccountServerUnavailable, "server account non disponibile"),
            new(GameTextKeys.Login.ServerError, "errore server"),
            new(GameTextKeys.Login.ServerTimeout, "timeout risposta server"),

            new(GameTextKeys.Account.SessionUsedElsewhere, "Il tuo account è stato usato su un altro dispositivo."),
            new(GameTextKeys.Account.SessionClosedBody, "{0}\n\nQuesta sessione è stata chiusa."),
            new(GameTextKeys.Account.CloseGame, "CHIUDI IL GIOCO"),
            new(GameTextKeys.Account.ReturnToLogin, "TORNA AL LOGIN"),

            new(GameTextKeys.PvpLoadout.Title, "ARSENALE"),
            new(GameTextKeys.PvpLoadout.Subtitle, "Componi una squadra equilibrata per l'arena"),
            new(GameTextKeys.PvpLoadout.Save, "SALVA"),
            new(GameTextKeys.PvpLoadout.Catalog, "CATALOGO CARTE"),
            new(GameTextKeys.PvpLoadout.ChooseRemaining, "scegli ancora {0} carte"),
            new(GameTextKeys.PvpLoadout.Valid, "loadout valido!"),
            new(GameTextKeys.PvpLoadout.Summary, "{0}/{1} CARTE     {2}/{3} BUDGET\n{4}"),
            new(GameTextKeys.PvpLoadout.MissingDatabase, "CardDatabase non assegnato: verrà usato il loadout predefinito."),
            new(GameTextKeys.PvpLoadout.SelectedSuffix, "  - SCELTA"),
            new(GameTextKeys.PvpLoadout.InspectionBody, "Classe: {0}\nPotenza: {1}\nCosto loadout: {2}\n\n{3}"),
            new(GameTextKeys.PvpLoadout.Add, "AGGIUNGI"),
            new(GameTextKeys.PvpLoadout.AlreadyAdded, "GIÀ NEL LOADOUT"),
            new(GameTextKeys.PvpLoadout.Full, "LOADOUT PIENO"),
            new(GameTextKeys.PvpLoadout.YourLoadout, "IL TUO LOADOUT"),
            new(GameTextKeys.PvpLoadout.RemoveHint, "Tocca una carta per rimuoverla"),
            new(GameTextKeys.PvpLoadout.CardPower, "{0}\nPOTENZA {1}"),

            new(GameTextKeys.PvpResult.Victory, "VITTORIA"),
            new(GameTextKeys.PvpResult.Defeat, "SCONFITTA"),
            new(GameTextKeys.PvpResult.Title, "RISULTATO ARENA"),
            new(GameTextKeys.PvpResult.VictorySubtitle, "La tua leggenda avanza"),
            new(GameTextKeys.PvpResult.DefeatSubtitle, "Riorganizza il loadout e torna in arena"),
            new(GameTextKeys.PvpResult.Continue, "CONTINUA"),
            new(GameTextKeys.PvpResult.Timeout, "Vittoria/sconfitta per tempo scaduto."),
            new(GameTextKeys.PvpResult.OpponentForfeit, "L'avversario ha abbandonato."),
            new(GameTextKeys.PvpResult.Surrendered, "Ti sei arreso."),
            new(GameTextKeys.PvpResult.OpponentSurrendered, "HAI VINTO: IL TUO AVVERSARIO SI È ARRESO"),
            new(GameTextKeys.PvpResult.Placement, "Piazzamento: {0} partite rimaste."),
            new(GameTextKeys.PvpResult.League, "{0} {1} — {2} LP  ({3}{4} LP)"),
            new(GameTextKeys.PvpResult.Promoted, "PROMOSSO!"),
            new(GameTextKeys.PvpResult.Demoted, "Retrocesso."),
            new(GameTextKeys.PvpResult.Friendly, "Partita amichevole (nessuna variazione di rank)."),
            new(GameTextKeys.PvpResult.Achievements, "TRAGUARDI SBLOCCATI:"),
            new(GameTextKeys.PvpResult.AchievementItem, "• {0}"),
            new(GameTextKeys.PvpResult.TripleExperienceOffer, "ADV  ×3 EXP ({0})"),
            new(GameTextKeys.PvpResult.TripleExperienceApplied, "EXP TRIPLICATA: +{0}"),
            new(GameTextKeys.PvpResult.TripleExperienceUnavailable, "ADV NON DISPONIBILE"),
            new(GameTextKeys.PvpResult.SurrenderLobbyStatus, "Ti sei arreso: la vittoria è andata all'avversario."),

            new(GameTextKeys.PvpStatus.ReconnectRemaining, "Partita ripresa: restano {0}s di riconnessione per questo match."),
            new(GameTextKeys.PvpStatus.ReconnectExpired, "Partita ripresa: hai esaurito il tempo di riconnessione, un'altra caduta è sconfitta."),
            new(GameTextKeys.PvpStatus.SurrenderNotSent, "Resa non inviata: connessione persa."),
            new(GameTextKeys.PvpStatus.MoveRejected, "Mossa rifiutata dal server."),
            new(GameTextKeys.PvpStatus.ActionNotConfirmed, "Mossa non confermata dal server: riprova."),
            new(GameTextKeys.PvpStatus.ActionNotSent, "Mossa non inviata: connessione persa."),

            new(GameTextKeys.PvpLog.MatchAgainst, "Match contro {0}."),
            new(GameTextKeys.PvpLog.RoundStarted, "--- Round {0}: dado vigore D{1} ---"),
            new(GameTextKeys.PvpLog.DecisiveSelection, "Round decisivo: scegli {0} carte tra tutte le 9."),
            new(GameTextKeys.PvpLog.DeploymentStarted, "Iniziative schieramento: {0} apre la sequenza."),
            new(GameTextKeys.PvpLog.CardDeployed, "{0} schiera {1} ({2})."),
            new(GameTextKeys.PvpLog.Auras, "Aure: {0} contro {1}."),
            new(GameTextKeys.PvpLog.TurnSkipped, "{0} è inibito e salta il turno."),
            new(GameTextKeys.PvpLog.CardRevived, "{0} torna in gioco con {1} vita."),
            new(GameTextKeys.PvpLog.ProtectionRedirect, "{0} devia l'attacco su di sé."),
            new(GameTextKeys.PvpLog.ProtectionAdvantage, "{0} si difende con vantaggio."),
            new(GameTextKeys.PvpLog.Attachment, "{0} si sacrifica: +{1} a {2}."),
            new(GameTextKeys.PvpLog.Fury, "{0} entra in Furia (+{1})."),
            new(GameTextKeys.PvpLog.MightAura, "Aura Might: {0} guadagna +1 permanente."),
            new(GameTextKeys.PvpLog.MageAura, "Aura Mago: {0} subisce -{1} permanente."),
            new(GameTextKeys.PvpLog.SpiritExpired, "Lo spirito di {0} svanisce."),
            new(GameTextKeys.PvpLog.Timeout, "Tempo scaduto per {0} ({1}° timeout)."),
            new(GameTextKeys.PvpLog.Forfeit, "{0} abbandona: vittoria a {1}."),
            new(GameTextKeys.PvpLog.RoundEnded, "Round {0} a {1}. Parziale {2}-{3}."),
            new(GameTextKeys.PvpLog.ReplayMismatch, "Risultato ricevuto dal server, ma il replay locale non mostra ancora una formazione eliminata."),
            new(GameTextKeys.PvpLog.WonByForfeit, "HAI VINTO PER ABBANDONO DELL'AVVERSARIO!"),
            new(GameTextKeys.PvpLog.LostByForfeit, "Hai perso per abbandono."),
            new(GameTextKeys.PvpLog.WonMatch, "HAI VINTO IL MATCH {0}-{1}!"),
            new(GameTextKeys.PvpLog.LostMatch, "Hai perso il match {0}-{1}."),
            new(GameTextKeys.PvpLog.Assassin, "{0} inibisce {1}."),
            new(GameTextKeys.PvpLog.Mage, "{0} abbassa il dado di {1} di {2} step."),
            new(GameTextKeys.PvpLog.Hunter, "{0} marca {1} (+{2} a chi lo attacca)."),
            new(GameTextKeys.PvpLog.PaladinSelf, "{0} si prepara a difendersi con vantaggio."),
            new(GameTextKeys.PvpLog.PaladinOther, "{0} protegge {1}."),
            new(GameTextKeys.PvpLog.Priest, "{0} benedice {1} (+{2})."),
            new(GameTextKeys.PvpLog.Warrior, "{0} prepara un colpo a due dadi."),
            new(GameTextKeys.PvpLog.Necromancer, "{0} rialza {1}."),
            new(GameTextKeys.PvpLog.CounterattackPrefix, "CONTRATTACCO: "),
            new(GameTextKeys.PvpLog.OverkillTag, " OVERKILL!"),
            new(GameTextKeys.PvpLog.Impossible, "attacco impossibile, turno perso"),
            new(GameTextKeys.PvpLog.RollOutcome, "{0} contro {1} ({2}; {3})"),
            new(GameTextKeys.PvpLog.Resists, " {0} resiste."),
            new(GameTextKeys.PvpLog.BecomesSpirit, "{0} {1} resta come spirito!"),
            new(GameTextKeys.PvpLog.Eliminated, "{0} {1} eliminato!"),
            new(GameTextKeys.PvpLog.LosesLife, " {0} perde una vita ({1})."),
            new(GameTextKeys.PvpLog.Attack, "{0}{1} attacca {2}: {3}.{4}"),
            new(GameTextKeys.PvpLog.RollSingle, "{0} {1}:{2}"),
            new(GameTextKeys.PvpLog.RollDouble, "{0} {1}[{2},{3}] {4}:{5}"),
            new(GameTextKeys.PvpLog.RollHighest, "max"),
            new(GameTextKeys.PvpLog.RollLowest, "min"),
            new(GameTextKeys.PvpLog.RollSum, "somma"),
            new(GameTextKeys.PvpLog.RollResult, "risultato"),
            new(GameTextKeys.PvpLog.UnknownPlayer, "G{0}"),
            new(GameTextKeys.PvpLog.SurrenderSent, "PVP - resa inviata al server."),
            new(GameTextKeys.PvpError.ManaInsufficient, "Mana insufficiente: servono {0}, disponibili {1}."),
            new(GameTextKeys.PvpError.ManaInsufficientGeneric, "Mana insufficiente per eseguire l'azione."),
            new(GameTextKeys.PvpError.SupremeNotAvailable, "La suprema non è ancora disponibile."),
            new(GameTextKeys.PvpError.TurnEndedWaiting, "Turno concluso. In attesa del server..."),
            new(GameTextKeys.PvpError.Surrendered, "Ti sei arreso: la vittoria va all'avversario."),
            new(GameTextKeys.PvpError.AbilityRequiresAction, "Dopo aver usato un'abilitÃ  devi attaccare o equipaggiarti."),

            new(GameTextKeys.Audio.VolumePercent, "{0}%"),

            new(GameTextKeys.Combat.OutcomeEliminated, "eliminata"),
            new(GameTextKeys.Combat.OutcomeResists, "resiste"),
            new(GameTextKeys.Combat.ResultDetailed, "{0}: {1} [{2}] contro {3} [{4}] - {5}."),
            new(GameTextKeys.Combat.ResultEliminates, "{0} elimina {1}."),
            new(GameTextKeys.Combat.ResultResists, "{0} resiste all'attacco di {1}."),
            new(GameTextKeys.Combat.ImpossibleAttackDetailed, "0%: {0} arriva al massimo a {1} ({2}{3} + {4}), mentre {5} parte da {6} ({7}{8} + D{9}:1)."),
            new(GameTextKeys.Combat.BonusAuraWarrior, "Aura Guerriero +2"),
            new(GameTextKeys.Combat.BonusHunterPrey, "Preda Hunter +{0}"),
            new(GameTextKeys.Combat.BonusFury, "Furia +{0}"),
            new(GameTextKeys.Combat.BonusEquipmentMalus, "Equip/Malus"),
            new(GameTextKeys.Combat.BonusMightAura, "Aura Forzuta"),
            new(GameTextKeys.Combat.BonusOther, "Altro"),
            new(GameTextKeys.Combat.BonusSourceFury, "Furia"),
            new(GameTextKeys.Combat.BonusSourceBlessing, "Benedizione"),
            new(GameTextKeys.Combat.BonusSourceGeneric, "Bonus"),
            new(GameTextKeys.Combat.DeploymentComplete, "Schieramento completato: in combattimento agiscono prima le iniziative piu alte."),
            new(GameTextKeys.Combat.InitiativeBanner, "INIZIATIVE  -  TUTTI I D20 IN LANCIO"),
            new(GameTextKeys.Combat.InitiativeStarted, "Tiro di iniziativa: ogni carta lancia un D20."),
            new(GameTextKeys.Combat.InitiativeLog, "INIZIATIVA {0} - {1}: D{2} = {3}"),
            new(GameTextKeys.Combat.InitiativeCallout, "INIZIATIVA {0}"),
            new(GameTextKeys.Combat.ActionAttack, "Attacca"),
            new(GameTextKeys.Combat.ActionAbility, "Abilit\u00E0"),
            new(GameTextKeys.Combat.ActionEquip, "Equipaggia"),
            new(GameTextKeys.Combat.ActionSkip, "Salta"),
            new(GameTextKeys.Combat.ActionChangeForm, "Cambia forma"),
            new(GameTextKeys.Combat.ActionSupreme, "Suprema"),
            new(GameTextKeys.Combat.SkipTurnMessage, "{0} salta il turno."),
            new(GameTextKeys.Combat.SkipTurnLog, "SALTA - {0} passa senza agire."),
            new(GameTextKeys.Combat.InhibitedSkipsTurn, "{0} e inibito e salta il turno."),
            new(GameTextKeys.Combat.PlayerTurnBanner, "IL TUO TURNO"),
            new(GameTextKeys.Combat.ChooseAction, "Scegli un'azione sopra la pedina o ispeziona una carta."),
            new(GameTextKeys.Combat.CpuTurnBanner, "TURNO CPU  -  {0}"),
            new(GameTextKeys.Combat.CpuChoosingTarget, "Turno CPU: {0} sta scegliendo un bersaglio..."),
            new(GameTextKeys.Combat.CpuPaladinRedirect, "PALADINO CPU: {0} devia su di se l'attacco diretto a {1}."),
            new(GameTextKeys.Combat.CpuPaladinSelfDefense, "PALADINO CPU: {0} si difende con vantaggio."),
            new(GameTextKeys.Combat.PlayerTurnSkippedSuffix, " Turno saltato."),
            new(GameTextKeys.Combat.ImpossiblePlayerAttack, "Attacco impossibile: turno saltato."),
            new(GameTextKeys.Combat.GuaranteedKill, "100%: {0} elimina direttamente {1}. Nessun dado necessario."),
            new(GameTextKeys.Combat.CpuTargetChoiceLog, "CPU: {0} sceglie {1} - {2}."),
            new(GameTextKeys.Combat.PaladinRedirect, "PALADINO: {0} devia su di se l'attacco diretto a {1}."),
            new(GameTextKeys.Combat.PaladinSelfDefense, "PALADINO: {0} si difende con vantaggio."),
            new(GameTextKeys.Combat.CpuTurnSkippedSuffix, " La CPU salta il turno."),
            new(GameTextKeys.Combat.ImpossibleCpuAttack, "Attacco CPU impossibile: turno saltato."),
            new(GameTextKeys.Combat.AttackTargetPrompt, "ATTACCO: scegli una pedina avversaria da colpire con {0}."),
            new(GameTextKeys.Combat.AssassinTargetPrompt, "ABILITA ASSASSINO: scegli un nemico da inibire."),
            new(GameTextKeys.Combat.WarriorAbilityReady, "ABILITA GUERRIERO: {0} sommerà il dado Vigore e un dado di uno step inferiore nel prossimo attacco."),
            new(GameTextKeys.Combat.MageTargetPrompt, "ABILITA MAGO: scegli un nemico a cui applicare un malus cumulabile al dado Vigore."),
            new(GameTextKeys.Combat.PaladinTargetPrompt, "ABILITA PALADINO: scegli una pedina alleata o {0} stesso da proteggere."),
            new(GameTextKeys.Combat.HunterTargetPrompt, "ABILITA CACCIATORE: scegli un nemico da marcare."),
            new(GameTextKeys.Combat.NecromancerTargetPrompt, "ABILITA NECROMANTE: scegli una carta alleata eliminata da rialzare."),
            new(GameTextKeys.Combat.PriestTargetPrompt, "ABILITA SACERDOTE: scegli una carta alleata da benedire."),
            new(GameTextKeys.Combat.AttachmentTargetPrompt, "Puoi equipaggiare questa carta sacrificandola, aumentando di +{0} la forza di una carta alleata."),
            new(GameTextKeys.Combat.AutoVictoryLog, "AUTO-VITTORIA - la CPU non ha attacchi possibili, abilita disponibili o equip utili: la stanza viene risolta automaticamente."),
            new(GameTextKeys.Combat.AutoVictoryMessage, "AUTO-VITTORIA: la CPU non puo piu colpirti ne usare azioni utili."),
            new(GameTextKeys.Combat.AttachmentApplied, "POTENZIA: {0} viene sacrificata e potenzia {1} di +{2} per tutta la battaglia."),
            new(GameTextKeys.Combat.AttachmentAppliedLog, "POTENZIA - {0} sacrificata: {1} ottiene +{2} permanente."),
            new(GameTextKeys.Combat.CpuAttachmentApplied, "CPU POTENZIA: {0} viene sacrificata e potenzia {1} di +{2} per tutta la battaglia."),
            new(GameTextKeys.Combat.CpuAttachmentAppliedLog, "CPU POTENZIA - {0} sacrificata: {1} ottiene +{2} permanente."),
            new(GameTextKeys.Combat.SpiritLastTurnEndedLog, "ULTIMO TURNO - {0} svanisce dopo aver agito."),
            new(GameTextKeys.Combat.GolemNewFormLog, "GOLEM - nuova forma attiva: {0}."),
            new(GameTextKeys.Combat.AuraActiveLog, "AURA ATTIVA - {0}"),
            new(GameTextKeys.Combat.CpuAuraActiveLog, "AURA CPU ATTIVA - {0}"),
            new(GameTextKeys.Combat.ManaInsufficientAbility, "Mana insufficiente per l'abilita di {0}."),
            new(GameTextKeys.Combat.RollDefenseNamed, "DIFESA {0}"),
            new(GameTextKeys.Combat.RollAttackNamed, "ATTACCO {0}"),
            new(GameTextKeys.Combat.RogueRerollStatus, "REROLL 1-{0} SE SERVE"),
            new(GameTextKeys.Combat.RollAttack, "ATTACCO"),
            new(GameTextKeys.Combat.RollDefense, "DIFESA"),
            new(GameTextKeys.Combat.RollCpuAttack, "ATTACCO CPU"),
            new(GameTextKeys.Combat.RollYourDefense, "TUA DIFESA"),
            new(GameTextKeys.Combat.DisadvantageAgainst, "Svantaggio contro {0}"),

            new(GameTextKeys.Options.ReturnToMenuTitle, "USCIRE AL MENU?"),
            new(GameTextKeys.Options.ReturnToMenuBody, "La campagna in corso verra' abbandonata. I progressi di questa sessione andranno persi."),
            new(GameTextKeys.Options.MainMenu, "MENU"),
            new(GameTextKeys.Options.Surrender, "ARRENDITI"),
            new(GameTextKeys.Options.SurrenderTitle, "ARRENDERSI?"),
            new(GameTextKeys.Options.SurrenderBody, "Ti arrendi: la partita e' persa e la vittoria va al tuo avversario."),
            new(GameTextKeys.Options.Title, "OPZIONI"),
            new(GameTextKeys.Options.SectionAudio, "AUDIO"),
            new(GameTextKeys.Options.SectionLanguage, "LINGUA"),
            new(GameTextKeys.Options.SectionGame, "GIOCO"),
            new(GameTextKeys.Options.SfxVolume, "EFFETTI"),
            new(GameTextKeys.Options.MusicVolume, "MUSICA"),
            new(GameTextKeys.Options.LanguageLabel, "LINGUA DI GIOCO"),
            new(GameTextKeys.Options.LanguageUnavailable, "NON DISPONIBILE"),
            new(GameTextKeys.Options.Log, "REGISTRO"),
            new(GameTextKeys.Options.AuraCodex, "AURE"),
            new(GameTextKeys.Options.Privacy, "PRIVACY"),
            new(GameTextKeys.Options.Logout, "LOGOUT"),
            new(GameTextKeys.GameLog.EntryContext, "[STANZA {0} / ROUND {1}] {2}"),

            new(GameTextKeys.Campaign.Advance, "VAI AVANTI!"),
            new(GameTextKeys.Campaign.RetryRoom, "RIPROVA STANZA"),
            new(GameTextKeys.Campaign.GolemRetryStatePreservedLog, "GOLEM - {0}/{1} HP e bonus Potenza delle forme conservati per il nuovo tentativo."),
            new(GameTextKeys.Campaign.RewardQueuedLog, "ACCOUNT - reward fine campagna ({0}) salvata: verra' registrata alla riconnessione."),
            new(GameTextKeys.Campaign.RewardNotRecordedLog, "ACCOUNT - reward fine campagna ({0}) non registrata: server non disponibile e account assente."),
            new(GameTextKeys.Campaign.OfflineSummarySaved, "Riepilogo della run salvato: EXP, statistiche e quest verranno sincronizzati alla riconnessione."),
            new(GameTextKeys.Campaign.RewardConnectionRequired, "Connessione al server necessaria per registrare la ricompensa di fine campagna."),
            new(GameTextKeys.Campaign.AdMultiplierConnectionRequired, "Connessione al server necessaria per applicare il moltiplicatore."),
            new(GameTextKeys.Campaign.AdUnavailable, "Nessuna pubblicita' disponibile in questo momento: riprova piu' tardi."),
            new(GameTextKeys.Campaign.AdWatchIncomplete, "Il video va guardato per intero per triplicare l'EXP."),
            new(GameTextKeys.Campaign.AdMultiplierNotAppliedLog, "ACCOUNT - moltiplicatore ADV non applicato: {0}."),
            new(GameTextKeys.Campaign.TripleSavedToProfile, "Il triplicatore ti aspetta fra i messaggi del profilo."),
            new(GameTextKeys.Campaign.DeckExhaustedBanner, "CAMPAGNA TERMINATA  -  MAZZO ESAURITO"),
            new(GameTextKeys.Campaign.NotEnoughCards, "Non hai abbastanza carte disponibili: {0}/{1}. Cimitero: {2}. Calcolo della ricompensa di fine campagna."),
            new(GameTextKeys.Campaign.ChapterCompleted, "completato"),
            new(GameTextKeys.Campaign.ChapterUnlockFirst, "sblocca il primo capitolo"),
            new(GameTextKeys.Campaign.ChapterUnlocked, "sbloccato"),
            new(GameTextKeys.Campaign.ChapterHoneySanctuary, "al santuario: {0} miele"),
            new(GameTextKeys.Campaign.ChapterComingSoon, "in arrivo"),
            new(GameTextKeys.Campaign.DefeatFormationBanner, "SCONFITTA  -  FORMAZIONE ELIMINATA"),
            new(GameTextKeys.Campaign.DefeatRetreatBanner, "SCONFITTA - RITIRATA"),
            new(GameTextKeys.Campaign.RoomReward, "Hai guadagnato {0} punti esperienza e {1} oro!"),
            new(GameTextKeys.Campaign.AccountRewardSummary, "Fine campagna: +{0} EXP account ({1}/10)."),
            new(GameTextKeys.Campaign.WatchAdToTriple, "Guarda ADV per triplicare la ricompensa."),
            new(GameTextKeys.Campaign.TripleQuestion, "Vuoi triplicare la ricompensa?"),
            new(GameTextKeys.Campaign.TripleQuestionWithAd, "Vuoi triplicare la ricompensa guardando una pubblicità?"),
            new(GameTextKeys.Campaign.RewardReady, "La ricompensa è pronta."),
            new(GameTextKeys.Campaign.RewardPopupBody, "Hai guadagnato\n<size=40><b>+{0} EXP</b></size>\n\n{1}"),
            new(GameTextKeys.Campaign.Triple, "TRIPLICA"),
            new(GameTextKeys.Campaign.WatchAdExperience, "GUARDA ADV EXP"),

            new(GameTextKeys.Adventure.ClassChoiceTitle, "SCEGLI UNA NUOVA CLASSE"),
            new(GameTextKeys.Adventure.ClassChoiceBody, "Hai completato il primo scenario. La classe scelta verra sbloccata permanentemente."),
            new(GameTextKeys.Adventure.ClassChoiceFinal, "La scelta e definitiva."),
            new(GameTextKeys.Adventure.ClassChoiceTestComplete, "TEST COMPLETATO: {0} SELEZIONATO"),
            new(GameTextKeys.Adventure.ClassChoiceUnlocking, "Sblocco in corso..."),
            new(GameTextKeys.Adventure.ClassChoiceFailed, "Scelta non registrata: {0}"),
            new(GameTextKeys.Adventure.ClassChoiceConnectionRequired, "Connessione al server non disponibile."),
            new(GameTextKeys.Adventure.ClassUnlockedLog, "PROGRESSIONE - classe scelta e sbloccata: {0}."),
            new(GameTextKeys.Adventure.ChapterClearQueuedLog, "AVVENTURA - completamento capitolo {0} salvato: verra' registrato alla riconnessione."),
            new(GameTextKeys.Adventure.ChapterClearNotRecordedLog, "AVVENTURA - completamento capitolo {0} non registrato: server non disponibile e account assente."),
            new(GameTextKeys.Adventure.TutorialConnectionRequired, "Connessione al server necessaria per registrare il completamento del tutorial."),
            new(GameTextKeys.Adventure.ChapterLockedMessage, "Capitolo chiuso: batti il boss del capitolo precedente, oppure compralo al Santuario per {0} miele."),
            new(GameTextKeys.Adventure.ChapterComingSoonMessage, "{0} arrivera' presto: il suo boss non e' ancora pronto."),
            new(GameTextKeys.Adventure.HardcoreConnectionRequired, "Connessione al server necessaria per sbloccare Hardcore."),

            new(GameTextKeys.Merchant.NoMoreCards, "MERCATO: il mercante non ha altre carte da offrirti."),
            new(GameTextKeys.Merchant.InsufficientExperience, "MERCATO: servono {0} EXP, disponibili {1}."),
            new(GameTextKeys.Merchant.UnknownCard, "una carta ignota"),
            new(GameTextKeys.Merchant.BranchCards, "CARTE"),
            new(GameTextKeys.Merchant.BranchItems, "OGGETTI"),
            new(GameTextKeys.Merchant.BranchConfirmTitle, "SCEGLI IL BANCO {0}"),
            new(GameTextKeys.Merchant.BranchConfirmBody, "Stai per acquistare {0} per {1} oro. Questo primo acquisto chiuderà il banco {2} fino alla prossima stanza Mercato.\n\nVuoi procedere?"),
            new(GameTextKeys.Merchant.RecoverInsufficientExperience, "MERCATO: servono {0} EXP per recuperare {1}, disponibili {2}."),
            new(GameTextKeys.Merchant.GoldAvailable, "ORO DISPONIBILE  <size=30>{0}</size>"),
            new(GameTextKeys.Merchant.InsufficientGold, "MERCATO: servono {0} oro, disponibili {1}."),
            new(GameTextKeys.Merchant.Sell, "VENDI"),
            new(GameTextKeys.Merchant.Recover, "RECUPERA"),
            new(GameTextKeys.Merchant.SelectCard, "SELEZIONA CARTA"),
            new(GameTextKeys.Merchant.SellForGold, "VENDI  +{0} ORO"),
            new(GameTextKeys.Merchant.RecoverForGold, "RECUPERA  -{0} ORO"),
            new(GameTextKeys.Merchant.GoldPrice, "{0} ORO"),
            new(GameTextKeys.Merchant.GoldCounter, "ORO {0}"),
            new(GameTextKeys.Merchant.MysteryPurchasePrefix, "CARTA IGNOTA: "),
            new(GameTextKeys.Merchant.PurchasePrefix, "ACQUISTO: "),
            new(GameTextKeys.Merchant.CardPurchaseLog, "ACQUISTO - {0}, -{1} oro (tassa di carovana inclusa)."),
            new(GameTextKeys.Merchant.CardPurchased, "{0}{1} entra nel mazzo per {2} oro. Oro disponibile: {3}."),
            new(GameTextKeys.Merchant.ItemPurchaseLog, "ACQUISTO OGGETTO - {0}, -{1} oro (tassa di carovana inclusa)."),
            new(GameTextKeys.Merchant.ItemPurchased, "ACQUISTO: {0} entra nella borsa per {1} oro. Oro disponibile: {2}."),
            new(GameTextKeys.Merchant.SoldLog, "VENDITA - {0}, +{1} oro."),
            new(GameTextKeys.Merchant.Sold, "VENDUTA: {0}. Ottieni {1} oro."),
            new(GameTextKeys.Merchant.RecoverInsufficientGold, "MERCATO: servono {0} oro per recuperare {1}, disponibili {2}."),
            new(GameTextKeys.Merchant.RecoveredLog, "RECUPERO MERCATO - {0} torna nel mazzo, -{1} oro."),
            new(GameTextKeys.Merchant.Recovered, "RECUPERATA: {0} torna nel mazzo per {1} oro. Ora puoi venderla o tenerla."),

            new(GameTextKeys.Profile.TabOverview, "PANORAMICA"),
            new(GameTextKeys.Profile.TabStatistics, "STATISTICHE"),
            new(GameTextKeys.Profile.TabAchievements, "TRAGUARDI"),
            new(GameTextKeys.Profile.TabMessages, "MESSAGGI"),
            new(GameTextKeys.Profile.Loading, "CARICAMENTO..."),
            new(GameTextKeys.Profile.NoMessages, "NESSUNA COMUNICAZIONE"),
            new(GameTextKeys.Profile.ExpiresHours, "SCADE FRA {0} H"),
            new(GameTextKeys.Profile.PendingRewardBody, "Hai guadagnato +{0} EXP, ma il triplicatore non e' stato riscosso.\nGuarda un video e ricevi altri +{1} EXP."),
            new(GameTextKeys.Profile.Triple, "TRIPLICA"),
            new(GameTextKeys.Profile.PendingReward, "RICOMPENSA IN SOSPESO"),
            new(GameTextKeys.Profile.Campaign, "CAMPAGNA"),
            new(GameTextKeys.Profile.CampaignEndRooms, "FINE {0} · {1} STANZE"),
            new(GameTextKeys.Profile.CampaignEnd, "FINE {0}"),
            new(GameTextKeys.Profile.Claiming, "Un attimo: sto riscuotendo..."),
            new(GameTextKeys.Profile.LoadingAd, "Un attimo: sto caricando la pubblicità..."),
            new(GameTextKeys.Profile.ConnectionRequired, "Connessione al server necessaria: la ricompensa resta qui."),
            new(GameTextKeys.Profile.AdUnavailable, "Nessuna pubblicità disponibile: la ricompensa resta qui, riprova più tardi."),
            new(GameTextKeys.Profile.AdIncomplete, "Il video va guardato per intero per triplicare l'EXP."),
            new(GameTextKeys.Profile.TripleApplied, "+{0} EXP account: ricompensa triplicata."),
            new(GameTextKeys.Profile.PendingLoadFailedLog, "PROFILO - ricompense in sospeso non caricate: {0}"),
            new(GameTextKeys.Profile.TripleNotAppliedLog, "PROFILO - triplicatore in sospeso non applicato: annuncio {0}."),
            new(GameTextKeys.Profile.TripleRecoveredLog, "PROFILO - triplicatore recuperato: +{0} EXP account."),
            new(GameTextKeys.Profile.TripleRejectedLog, "PROFILO - triplicatore in sospeso rifiutato dal server: {0}"),

            new(GameTextKeys.Tavern.Claiming, "Un attimo: sto riscuotendo..."),
            new(GameTextKeys.Tavern.LoadingAd, "Un attimo: sto caricando la pubblicità..."),
            new(GameTextKeys.Tavern.AdUnavailable, "Nessuna pubblicità disponibile in questo momento: la ricompensa resta qui, riprova più tardi."),
            new(GameTextKeys.Tavern.AdIncomplete, "La pubblicità va guardata per intero per riscuotere."),
            new(GameTextKeys.Tavern.ClaimNotUnlockedLog, "TAVERNA - riscossione non sbloccata: annuncio {0}."),

            new(GameTextKeys.Sanctuary.Title, "SANTUARIO"),
            new(GameTextKeys.Sanctuary.AltarClasses, "CLASSI"),
            new(GameTextKeys.Sanctuary.AltarTechniques, "TECNICHE"),
            new(GameTextKeys.Sanctuary.AltarRelics, "RELIQUIE"),
            new(GameTextKeys.Sanctuary.AltarChapters, "Capitoli"),
            new(GameTextKeys.Sanctuary.ChaptersStatus, "Ogni capitolo si guadagna battendo il boss di quello prima, oppure si compra qui."),
            new(GameTextKeys.Sanctuary.Loading, "Consulto l'alveare..."),
            new(GameTextKeys.Sanctuary.Reconnecting, "Riconnessione in corso: il Santuario si aggiornerà automaticamente."),
            new(GameTextKeys.Sanctuary.Offline, "Santuario non disponibile offline: serve la connessione al server."),
            new(GameTextKeys.Sanctuary.Unavailable, "Il Santuario non risponde: {0}"),
            new(GameTextKeys.Sanctuary.EmptyAltar, "Nessuna voce in questo altare."),
            new(GameTextKeys.Sanctuary.ClassesStatus, "Ogni classe chiede una prova guadagnata giocando, oltre al miele."),
            new(GameTextKeys.Sanctuary.TechniquesStatus, "Ogni tecnica chiede la classe corrispondente, oltre al miele."),
            new(GameTextKeys.Sanctuary.RelicsStatus, "Sblocca gli oggetti per renderli acquistabili al negozio. Slot bisaccia: {0}."),
            new(GameTextKeys.Sanctuary.OfferItem, "Sblocca {0} per {1} vasetti di miele: da quel momento il negozio potra' vendertelo. Lo sblocco non ti da' una copia."),
            new(GameTextKeys.Sanctuary.OfferSlot, "Apri uno slot in piu' nella bisaccia per {0} vasetti di miele."),
            new(GameTextKeys.Sanctuary.OfferTechnique, "Possiedi la classe. Offri {0} vasetti di miele per apprendere questa tecnica: sara' tua su ogni carta della classe."),
            new(GameTextKeys.Sanctuary.OfferChapter, "Apri questo capitolo per {0} vasetti di miele, senza battere il boss di quello prima. La classe in fondo al capitolo resta da guadagnare."),
            new(GameTextKeys.Sanctuary.OfferClass, "Hai superato le prove. Offri {0} vasetti di miele all'alveare per ricordare questa classe."),
            new(GameTextKeys.Sanctuary.HoneyAvailable, "{0}\n\nMiele disponibile: {1}."),
            new(GameTextKeys.Sanctuary.HoneyInsufficientBody, "Servono {0} vasetti di miele e ne hai {1}.\n\nTorna quando ne avrai abbastanza."),
            new(GameTextKeys.Sanctuary.OfferHoney, "OFFRI IL MIELE"),
            new(GameTextKeys.Sanctuary.HoneyInsufficient, "MIELE INSUFFICIENTE"),
            new(GameTextKeys.Sanctuary.ConnectionRequired, "Serve la connessione al server per offrire il miele."),
            new(GameTextKeys.Sanctuary.ItemUnlocked, "{0} sbloccato: ora il negozio puo' vendertelo."),
            new(GameTextKeys.Sanctuary.EntryOwned, "{0} ora e' tua."),
            new(GameTextKeys.Sanctuary.CardOwned, "OTTENUTA"),
            new(GameTextKeys.Sanctuary.CardComingSoon, "IN ARRIVO - {0} MIELE"),
            new(GameTextKeys.Sanctuary.CardFromTutorial, "DAL TUTORIAL"),
            new(GameTextKeys.Sanctuary.CardHoneyCost, "{0} MIELE"),
            new(GameTextKeys.Sanctuary.DiscoveryClasses, "CLASSI SCOPERTE"),
            new(GameTextKeys.Sanctuary.DiscoveryTechniques, "TECNICHE SCOPERTE"),
            new(GameTextKeys.Sanctuary.DiscoveryRelics, "RELIQUIE SCOPERTE"),
            new(GameTextKeys.Sanctuary.DiscoveryChapters, "CAPITOLI APERTI"),
            new(GameTextKeys.Sanctuary.CatalogReceivedLog, "SANTUARIO - catalogo ricevuto: {0} voci."),
            new(GameTextKeys.Sanctuary.NoConnectionLog, "SANTUARIO - nessuna connessione al server."),
            new(GameTextKeys.Sanctuary.CatalogFailedLog, "SANTUARIO - catalogo non ricevuto: {0}"),
            new(GameTextKeys.Sanctuary.PurchasedLog, "SANTUARIO - {0} acquistato per {1} miele."),
            new(GameTextKeys.Sanctuary.PurchaseRejectedLog, "SANTUARIO - acquisto {0} rifiutato: {1}"),

            new(GameTextKeys.Consumables.Name("detector"), "Detector"),
            new(GameTextKeys.Consumables.Name("second_chance"), "Seconda Chance"),
            new(GameTextKeys.Consumables.Name("defrost"), "Defrost"),
            new(GameTextKeys.Consumables.Name("empower"), "Empower"),
            new(GameTextKeys.Consumables.Name("ruby_seal"), "Sigillo Rubino"),
            new(GameTextKeys.Consumables.Name("double_experience"), "Doppia EXP"),
            new(GameTextKeys.Consumables.Name("generic"), "Consumabile"),
            new(GameTextKeys.Consumables.Description("detector"), "Rivela il contenuto delle tre porte nella prossima scelta della via. Le etichette compaiono sulle porte prima di entrare."),
            new(GameTextKeys.Consumables.Description("second_chance"), "Resuscita tutte le carte nel cimitero e le rimette nel mazzo. Non puo essere usata in battaglia."),
            new(GameTextKeys.Consumables.Description("defrost"), "Scongela tutte le carte in cooldown e le rimette nel mazzo. Non puo essere usata in battaglia."),
            new(GameTextKeys.Consumables.Description("empower"), "Aumenta di uno step il tuo dado Vigore in attacco per la stanza corrente o per la prossima stanza. Non puo essere usato nelle stanze Boss o Miniboss."),
            new(GameTextKeys.Consumables.Description("ruby_seal"), "Potenzia permanentemente di +2 una pedina schierata in campo. Ogni carta puo ricevere un solo Sigillo Rubino."),
            new(GameTextKeys.Consumables.Description("double_experience"), "Raddoppia tutta l'esperienza ottenuta nella prossima stanza."),
            new(GameTextKeys.Consumables.Description("generic"), "Oggetto consumabile da campagna."),
            new(GameTextKeys.Consumables.CannotUseInBattle, "{0} non puo essere usato in battaglia."),
            new(GameTextKeys.Consumables.BlockedByBattleLog, "CONSUMABILE - {0} bloccato: battaglia in corso."),
            new(GameTextKeys.Consumables.EmpowerBossBlocked, "Empower non puo essere usato nelle stanze Boss o Miniboss."),
            new(GameTextKeys.Consumables.EmpowerBossBlockedLog, "CONSUMABILE - Empower bloccato: stanza Boss/Miniboss."),
            new(GameTextKeys.Consumables.DetectorRevealed, "Detector attivato: i destini delle tre porte sono rivelati."),
            new(GameTextKeys.Consumables.DetectorNextChoice, "Detector attivato: la prossima scelta porte mostrera il destino di ogni porta."),
            new(GameTextKeys.Consumables.DetectorActivatedLog, "CONSUMABILE - Detector attivato."),
            new(GameTextKeys.Consumables.SecondChanceUsed, "Seconda Chance: {0} carte tornano dal cimitero al mazzo."),
            new(GameTextKeys.Consumables.SecondChanceUsedLog, "CONSUMABILE - Seconda Chance recupera {0} carte."),
            new(GameTextKeys.Consumables.DefrostUsed, "Defrost: {0} carte tornano dal cooldown al mazzo."),
            new(GameTextKeys.Consumables.DefrostUsedLog, "CONSUMABILE - Defrost libera {0} carte."),
            new(GameTextKeys.Consumables.EmpowerUsed, "Empower attivato: il tuo dado Vigore in attacco sale di uno step per questa stanza o la prossima."),
            new(GameTextKeys.Consumables.EmpowerUsedLog, "CONSUMABILE - Empower pronto: dado Vigore d'attacco +1 step nella stanza corrente o prossima."),
            new(GameTextKeys.Consumables.DoubleExperienceReady, "Doppia EXP attivata: la prossima stanza dara esperienza doppia."),
            new(GameTextKeys.Consumables.DoubleExperienceReadyLog, "CONSUMABILE - Doppia EXP pronta per la prossima stanza."),
            new(GameTextKeys.Consumables.RubySealNoTarget, "Sigillo Rubino: nessuna pedina valida schierata in campo."),
            new(GameTextKeys.Consumables.RubySealNoTargetLog, "CONSUMABILE - Sigillo Rubino bloccato: nessun bersaglio valido."),
            new(GameTextKeys.Consumables.RubySealSelectTarget, "Sigillo Rubino pronto: scegli una pedina schierata in campo."),
            new(GameTextKeys.Consumables.RubySealSelectTargetLog, "CONSUMABILE - Sigillo Rubino: scelta bersaglio attiva."),
            new(GameTextKeys.Consumables.RubySealTargetTitle, "SIGILLO RUBINO - SCEGLI UNA PEDINA SCHIERATA"),
            new(GameTextKeys.Consumables.RubySealInvalidTarget, "Sigillo Rubino: scegli una pedina schierata, attiva e non ancora sigillata."),
            new(GameTextKeys.Consumables.RubySealAlreadyApplied, "Sigillo Rubino: questa carta e' gia' sigillata."),
            new(GameTextKeys.Consumables.RubySealApplied, "Sigillo Rubino inciso su {0}: forza permanente +2."),
            new(GameTextKeys.Consumables.RubySealAppliedLog, "CONSUMABILE - Sigillo Rubino: {0} ottiene +2 permanente."),
            new(GameTextKeys.Consumables.GrantedLog, "{0} - ottieni consumabile {1}."),
            new(GameTextKeys.Consumables.GrantedDescription, " {0}: ottieni {1}."),
            new(GameTextKeys.Consumables.BagEmptyLog, "BISACCIA - vuota: nessun consumabile in questa run."),
            new(GameTextKeys.Consumables.BagLoadedLog, "BISACCIA - {0} consumabili portati in run."),
            new(GameTextKeys.Consumables.DoubleExperienceConsumedLog, "CONSUMABILE - Doppia EXP consumata."),
            new(GameTextKeys.Consumables.InspectionSummary, "{0}\n\n{1}\n\nQuantita: {2}\nUso singolo. Solo campagna."),

            new(GameTextKeys.Rules.HeroClassName("assassin"), "Assassino"),
            new(GameTextKeys.Rules.HeroClassName("warrior"), "Guerriero"),
            new(GameTextKeys.Rules.HeroClassName("mage"), "Mago"),
            new(GameTextKeys.Rules.HeroClassName("paladin"), "Paladino"),
            new(GameTextKeys.Rules.HeroClassName("rogue"), "Ladro"),
            new(GameTextKeys.Rules.HeroClassName("hunter"), "Cacciatore"),
            new(GameTextKeys.Rules.HeroClassName("barbarian"), "Barbaro"),
            new(GameTextKeys.Rules.HeroClassName("necromancer"), "Necromante"),
            new(GameTextKeys.Rules.HeroClassName("priest"), "Sacerdote"),
            new(GameTextKeys.Rules.FamilyName("might"), "Forzuta"),
            new(GameTextKeys.Rules.FamilyName("cunning"), "Astuta"),
            new(GameTextKeys.Rules.FamilyName("magic"), "Magica"),

            new(GameTextKeys.Rules.ShortAbility("rogue"), "IN ATTACCO: SE SERVE, RITIRA FINO AL SUO LIVELLO"),
            new(GameTextKeys.Rules.ShortAbility("hunter"), "MARCA UN NEMICO: +{0} AL PROSSIMO ATTACCO"),
            new(GameTextKeys.Rules.ShortAbility("barbarian"), "FURIA +{0} SE NON ELIMINA"),
            new(GameTextKeys.Rules.ShortAbility("necromancer"), "RIALZA UN ALLEATO ELIMINATO"),
            new(GameTextKeys.Rules.ShortAbility("priest"), "BENEDIZIONE +{0} A UN ALLEATO"),
            new(GameTextKeys.Rules.ShortAbility("assassin"), "SCEGLIE UN NEMICO: SALTA IL TURNO"),
            new(GameTextKeys.Rules.ShortAbility("warrior"), "PROSSIMO ATTACCO: SOMMA DADO VIGORE + DADO STEP -1"),
            new(GameTextKeys.Rules.ShortAbility("mage"), "MALUS CUMULABILE AL DADO VIGORE NEMICO"),
            new(GameTextKeys.Rules.ShortAbility("paladin"), "SI RAFFORZA O PROTEGGE UN ALLEATO"),

            new(GameTextKeys.Rules.AbilityDescription("warrior"), "Attiva l'abilita: al prossimo attacco tira il dado Vigore e un dado di uno step inferiore, poi somma i risultati."),
            new(GameTextKeys.Rules.AbilityDescription("barbarian"), "Se attacca ma non elimina il bersaglio, prepara Furia: +{0} al prossimo attacco e alla prossima difesa."),
            new(GameTextKeys.Rules.AbilityDescription("paladin"), "Il Paladino puo rafforzarsi o proteggere un alleato deviando un attacco su di se, si difendera con vantaggio."),
            new(GameTextKeys.Rules.AbilityDescription("rogue"), "Abilita passiva: quando attacca, se il totale non basta a vincere, ritira una volta ogni dado Vigore con un risultato pari o inferiore al suo livello. Se sta gia vincendo, non ritira."),
            new(GameTextKeys.Rules.AbilityDescription("assassin"), "Scegli un avversario: salta il suo prossimo turno."),
            new(GameTextKeys.Rules.AbilityDescription("hunter"), "Marca un nemico. Il prossimo attacco contro quel bersaglio riceve +{0}, poi tutti i marchi sul bersaglio vengono consumati. Piu marchi non si sommano."),
            new(GameTextKeys.Rules.AbilityDescription("mage"), "Scegli un nemico: nel prossimo confronto il suo dado Vigore scende di una taglia. Piu marchi si accumulano, fino a un minimo di D3."),
            new(GameTextKeys.Rules.AbilityDescription("necromancer"), "Riporta in vita un alleato eliminato che agisce subito dopo di te."),
            new(GameTextKeys.Rules.AbilityDescription("priest"), "Potenzia un alleato di +{0} al suo prossimo attacco."),
            new(GameTextKeys.Rules.NoCombatAbility, "Nessuna abilita di combattimento."),
            new(GameTextKeys.Rules.AbilityTitle, "Abilita {0}"),
            new(GameTextKeys.Rules.SupremeTitle, "Suprema di {0}"),
            new(GameTextKeys.Rules.SupremeLocked, "Tecnica non ancora appresa. Si sblocca al Santuario."),
            new(GameTextKeys.Rules.ManaCost, "{0} mana"),
            new(GameTextKeys.Rules.ManaCostFree, "Gratuita"),

            new(GameTextKeys.Rules.FamilyAura("might"), "Quando muore una pedina qualsiasi, ogni carta Forzuta con l'aura attiva acquisisce +1 permanente."),
            new(GameTextKeys.Rules.FamilyAura("cunning"), "Le carte Astute attaccano con vantaggio i nemici che hanno bonus o malus."),
            new(GameTextKeys.Rules.FamilyAura("magic"), "Le carte Magiche si difendono con un dado Vigore di una taglia superiore."),
            new(GameTextKeys.Rules.NoAura, "Nessun effetto."),

            new(GameTextKeys.Rules.ClassAura("warrior"), "Durante un confronto, se la Potenza del Guerriero e inferiore a quella dell'avversario, il Guerriero riceve +2 al totale."),
            new(GameTextKeys.Rules.ClassAura("barbarian"), "Furia vale +3 invece di +2, sia in attacco sia in difesa."),
            new(GameTextKeys.Rules.ClassAura("paladin"), "Quando un Paladino sopravvive a una difesa, contrattacca con +1."),
            new(GameTextKeys.Rules.ClassAura("rogue"), "L'abilita passiva del Ladro funziona anche in difesa: se il totale non basta a resistere, ritira una volta ogni dado Vigore con un risultato pari o inferiore al suo livello. Se sta gia resistendo, non ritira."),
            new(GameTextKeys.Rules.ClassAura("assassin"), "Quando un Assassino inibisce un nemico, quel nemico subisce anche -1 permanente."),
            new(GameTextKeys.Rules.ClassAura("hunter"), "Il prossimo attacco contro un bersaglio marcato riceve +{0} invece di +{1}; poi tutti i marchi sul bersaglio vengono consumati. I marchi non si sommano."),
            new(GameTextKeys.Rules.ClassAura("mage"), "Quando un Mago con questa aura muore per un attacco, l'attaccante che lo ha eliminato subisce -2 permanente."),
            new(GameTextKeys.Rules.ClassAura("necromancer"), "La prima volta che un alleato viene eliminato, resta in campo come Spirito per un ultimo turno."),
            new(GameTextKeys.Rules.ClassAura("priest"), "Benedizione vale +3 invece di +2."),
            new(GameTextKeys.Rules.FormationAura, "Si annulla lo svantaggio in attacco che diventa un tiro neutro.")
        };
    }
}
